services: 
  ros_eval:
    build:
      context: .
      dockerfile: .docker_utils/Dockerfile
      args:
        BASE_IMAGE: ros
        USERNAME: $USER
        USER_UID: $UID
        USER_GID: $GID
    image: maubrunner/ros_eval:x86
    profiles: [x86]
    container_name: ros_eval_container
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes: 
      - "./src:/home/${USER}/ros_eval/src"
      - "./plots:/home/${USER}/ros_eval/plots"
      - "./videos:/home/${USER}/ros_eval/videos"
      - "./cache:/home/${USER}/ros_eval/cache"
      # - "${HOME}/pbl/rosbags:/home/${USER}/data"
      - "./src/utils:/ros_eval/src/utils"
      - "./src/plot_helpers:/ros_eval/src/plot_helpers"

  ros_eval_arm:
    build:
      context: .
      dockerfile: .docker_utils/Dockerfile
      args:
        BASE_IMAGE: arm64v8/ros
        USERNAME: $USER
        USER_UID: $UID
        USER_GID: $GID
    image: maubrunner/ros_eval:arm
    profiles: [arm]
    container_name: ros_eval_container
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes: 
      - "./src:/home/${USER}/ros_eval/src"
      - "./plots:/home/${USER}/ros_eval/plots"
      - "./videos:/home/${USER}/ros_eval/videos"
      - "./cache:/home/${USER}/ros_eval/cache"
      # - "${HOME}/pbl/rosbags:/home/${USER}/data"
      - "./src/utils:/ros_eval/src/utils"
      - "./src/plot_helpers:/ros_eval/src/plot_helpers"

 
